Repository prgrms-be-devcourse/NBE1_2_Team04, pull requests merged in 2024-10, with the labels that each got.

#45 fix: #44 관련 메소드 수정
  src/main/java/team4/footwithme/stadium/service/CourtServiceImpl.java
Labels: 🔥BugFix, 노관태

#42 [refactor/#30] 투표 기능 리팩토링
  src/main/java/team4/footwithme/vote/api/VoteApi.java
  src/main/java/team4/footwithme/vote/domain/Vote.java
  src/main/java/team4/footwithme/vote/service/VoteService.java
  src/main/java/team4/footwithme/vote/service/VoteServiceImpl.java
  src/test/java/team4/footwithme/vote/domain/VoteTest.java
  src/test/java/team4/footwithme/vote/service/VoteServiceImplTest.java
Labels: 🔨Refactor, 나민혁

#47 [ fix/#42] 컴파일 에러 수정
  src/test/java/team4/footwithme/docs/vote/VoteApiDocs.java
Labels: 🔥BugFix, 나민혁

#43 [Feat/#33] 로그아웃, 회원 정보 수정, AccessToken 갱신 API
  src/main/java/team4/footwithme/config/SecurityConfig.java
  src/main/java/team4/footwithme/global/exception/ExceptionHandlerFilter.java
  src/main/java/team4/footwithme/member/api/MemberApi.java
  src/main/java/team4/footwithme/member/api/request/JoinRequest.java
  src/main/java/team4/footwithme/member/api/request/UpdatePasswordRequest.java
  src/main/java/team4/footwithme/member/api/request/UpdateRequest.java
  src/main/java/team4/footwithme/member/api/request/validation/PasswordMatches.java
  src/main/java/team4/footwithme/member/api/request/validation/PasswordMatchesValidator.java
  src/main/java/team4/footwithme/member/domain/Member.java
  src/main/java/team4/footwithme/member/jwt/JwtTokenFilter.java
  src/main/java/team4/footwithme/member/jwt/JwtTokenUtil.java
  src/main/java/team4/footwithme/member/jwt/PrincipalDetails.java
  src/main/java/team4/footwithme/member/repository/CustomMemberRepositoryImpl.java
  src/main/java/team4/footwithme/member/service/MemberService.java
  src/main/java/team4/footwithme/member/service/MemberServiceImpl.java
  src/main/java/team4/footwithme/member/service/request/UpdatePasswordServiceRequest.java
  src/main/java/team4/footwithme/member/service/request/UpdateServiceRequest.java
  src/test/java/team4/footwithme/docs/member/MemberApiDocs.java
  src/test/java/team4/footwithme/member/service/MemberServiceImplTest.java
Labels: ✨Feature, 문재경

#49 [Feat/#18] 구장 등록, 수정, 삭제 및 역할 설정
  src/main/java/team4/footwithme/stadium/api/CourtMerchantApi.java
  src/main/java/team4/footwithme/stadium/api/StadiumApi.java
  src/main/java/team4/footwithme/stadium/api/StadiumMerchantApi.java
  src/main/java/team4/footwithme/stadium/api/request/CourtDeleteRequest.java
  src/main/java/team4/footwithme/stadium/api/request/CourtRegisterRequest.java
  src/main/java/team4/footwithme/stadium/api/request/CourtUpdateRequest.java
  src/main/java/team4/footwithme/stadium/api/request/StadiumRegisterRequest.java
  src/main/java/team4/footwithme/stadium/api/request/StadiumSearchByLocationRequest.java
  src/main/java/team4/footwithme/stadium/api/request/StadiumUpdateRequest.java
  src/main/java/team4/footwithme/stadium/domain/Court.java
  src/main/java/team4/footwithme/stadium/domain/Stadium.java
  src/main/java/team4/footwithme/stadium/repository/CourtRepository.java
  src/main/java/team4/footwithme/stadium/repository/CustomStadiumRepositoryImpl.java
  src/main/java/team4/footwithme/stadium/repository/StadiumRepository.java
  src/main/java/team4/footwithme/stadium/service/CourtService.java
  src/main/java/team4/footwithme/stadium/service/CourtServiceImpl.java
  src/main/java/team4/footwithme/stadium/service/StadiumService.java
  src/main/java/team4/footwithme/stadium/service/StadiumServiceImpl.java
  src/main/java/team4/footwithme/stadium/service/request/CourtDeleteServiceRequest.java
  src/main/java/team4/footwithme/stadium/service/request/CourtRegisterServiceRequest.java
  src/main/java/team4/footwithme/stadium/service/request/CourtUpdateServiceRequest.java
  src/main/java/team4/footwithme/stadium/service/response/StadiumDetailResponse.java
Labels: ✨Feature, 노관태

#50 [Feat/#27] 팀 멤버 초대, 조회, 탈퇴 기능 구현
  src/main/java/team4/footwithme/team/api/TeamMemberApi.java
  src/main/java/team4/footwithme/team/api/request/TeamMemberRequest.java
  src/main/java/team4/footwithme/team/domain/TeamMember.java
  src/main/java/team4/footwithme/team/repository/CustomTeamRepository.java
  src/main/java/team4/footwithme/team/repository/CustomTeamRepositoryImpl.java
  src/main/java/team4/footwithme/team/repository/TeamMemberRepository.java
  src/main/java/team4/footwithme/team/repository/TeamRepository.java
  src/main/java/team4/footwithme/team/service/TeamMemberService.java
  src/main/java/team4/footwithme/team/service/TeamMemberServiceImpl.java
  src/main/java/team4/footwithme/team/service/TeamServiceImpl.java
  src/main/java/team4/footwithme/team/service/request/TeamMemberServiceRequest.java
  src/main/java/team4/footwithme/team/service/response/TeamInfoResponse.java
  src/main/java/team4/footwithme/team/service/response/TeamResponse.java
  src/test/java/team4/footwithme/docs/member/MemberApiDocs.java
  src/test/java/team4/footwithme/team/service/TeamMemberServiceImplTest.java
Labels: ✨Feature, 박윤영

#53 [feat/#41] 채팅 기능 일부 수정 및 Redis Topic 일원화
  src/main/java/team4/footwithme/chat/api/ChatMemberApi.java
  src/main/java/team4/footwithme/chat/api/request/ChatUpdateRequest.java
  src/main/java/team4/footwithme/chat/domain/Chat.java
  src/main/java/team4/footwithme/chat/domain/ChatType.java
  src/main/java/team4/footwithme/chat/repository/CustomChatMemberRepository.java
  src/main/java/team4/footwithme/chat/repository/CustomChatMemberRepositoryImpl.java
  src/main/java/team4/footwithme/chat/repository/RedisChatroomRepository.java
  src/main/java/team4/footwithme/chat/service/ChatMemberService.java
  src/main/java/team4/footwithme/chat/service/ChatMemberServiceImpl.java
  src/main/java/team4/footwithme/chat/service/ChatService.java
  src/main/java/team4/footwithme/chat/service/ChatServiceImpl.java
  src/main/java/team4/footwithme/chat/service/ChatroomServiceImpl.java
  src/main/java/team4/footwithme/chat/service/RedisPublisher.java
  src/main/java/team4/footwithme/chat/service/RedisSubscriber.java
  src/main/java/team4/footwithme/chat/service/request/ChatUpdateServiceRequest.java
  src/main/java/team4/footwithme/chat/service/response/ChatMemberResponse.java
  src/main/java/team4/footwithme/chat/service/response/ChatResponse.java
  src/main/java/team4/footwithme/config/redis/ExternalRedisConfig.java
  src/main/java/team4/footwithme/config/redis/RedisConfig.java
  src/main/java/team4/footwithme/global/exception/ExceptionMessage.java
Labels: ✨Feature, 황민우

#56 [Feat/#11] 투표 마감 기능 동적 스케줄링으로 구현
  src/main/java/team4/footwithme/config/AsyncConfig.java
  src/main/java/team4/footwithme/config/SchedulingConfig.java
  src/main/java/team4/footwithme/vote/domain/Vote.java
  src/main/java/team4/footwithme/vote/domain/VoteStatus.java
  src/main/java/team4/footwithme/vote/service/RegisteredVoteEvent.java
  src/main/java/team4/footwithme/vote/service/VoteEventHandler.java
  src/main/java/team4/footwithme/vote/service/VoteServiceImpl.java
  src/test/java/team4/footwithme/vote/domain/VoteTest.java
  src/test/java/team4/footwithme/vote/service/VoteServiceImplTest.java
Labels: ✨Feature, 나민혁

#58 [feat/#54] 팀 생성 및 팀원 초대에 따른 event 처리
  src/main/java/team4/footwithme/chat/api/ChatroomApi.java
  src/main/java/team4/footwithme/chat/domain/Chat.java
  src/main/java/team4/footwithme/chat/domain/Chatroom.java
  src/main/java/team4/footwithme/chat/domain/ReservationChatroom.java
  src/main/java/team4/footwithme/chat/domain/TeamChatroom.java
  src/main/java/team4/footwithme/chat/repository/ChatMemberRepository.java
  src/main/java/team4/footwithme/chat/repository/ChatroomRepository.java
  src/main/java/team4/footwithme/chat/repository/RedisChatroomRepository.java
  src/main/java/team4/footwithme/chat/service/ChatMemberService.java
  src/main/java/team4/footwithme/chat/service/ChatMemberServiceImpl.java
  src/main/java/team4/footwithme/chat/service/ChatroomService.java
  src/main/java/team4/footwithme/chat/service/ChatroomServiceImpl.java
  src/main/java/team4/footwithme/chat/service/event/ChatEventListener.java
  src/main/java/team4/footwithme/chat/service/event/ReservationDeletedEvent.java
  src/main/java/team4/footwithme/chat/service/event/ReservationMemberJoinEvent.java
  src/main/java/team4/footwithme/chat/service/event/ReservationMemberLeaveEvent.java
  src/main/java/team4/footwithme/chat/service/event/ReservationMembersJoinEvent.java
  src/main/java/team4/footwithme/chat/service/event/ReservationPublishedEvent.java
  src/main/java/team4/footwithme/chat/service/event/TeamDeletedEvent.java
  src/main/java/team4/footwithme/chat/service/event/TeamMemberJoinEvent.java
  src/main/java/team4/footwithme/chat/service/event/TeamMemberLeaveEvent.java
  src/main/java/team4/footwithme/chat/service/event/TeamMembersJoinEvent.java
  src/main/java/team4/footwithme/chat/service/event/TeamPublishedEvent.java
  src/main/java/team4/footwithme/config/redis/RedisConfig.java
  src/main/java/team4/footwithme/resevation/domain/Participant.java
  src/main/java/team4/footwithme/team/domain/Team.java
  src/main/java/team4/footwithme/team/repository/TeamMemberRepository.java
  src/main/java/team4/footwithme/team/service/TeamMemberServiceImpl.java
  src/main/java/team4/footwithme/team/service/TeamServiceImpl.java
  src/main/java/team4/footwithme/team/service/response/TeamDefaultResponse.java
Labels: ✨Feature, 황민우

#61 [Feat/#48] OAuth 2.0 로그인/회원가입 기능 개발
  build.gradle
  src/main/java/team4/footwithme/config/SecurityConfig.java
  src/main/java/team4/footwithme/member/api/request/LoginRequest.java
  src/main/java/team4/footwithme/member/api/request/UpdatePasswordRequest.java
  src/main/java/team4/footwithme/member/api/request/validation/PasswordMatchesValidator.java
  src/main/java/team4/footwithme/member/domain/Member.java
  src/main/java/team4/footwithme/member/domain/MemberRole.java
  src/main/java/team4/footwithme/member/jwt/JwtTokenUtil.java
  src/main/java/team4/footwithme/member/oauth2/CustomOAuth2LoginSuccessHandler.java
  src/main/java/team4/footwithme/member/oauth2/CustomOAuth2UserDetails.java
  src/main/java/team4/footwithme/member/oauth2/CustomOAuth2UserService.java
  src/main/java/team4/footwithme/member/oauth2/OAuth2GoogleMemberDetails.java
  src/main/java/team4/footwithme/member/oauth2/OAuth2MemberDetails.java
  src/main/java/team4/footwithme/member/oauth2/response/MemberOAuthResponse.java
  src/main/java/team4/footwithme/member/service/MemberServiceImpl.java
  src/test/java/team4/footwithme/docs/member/MemberApiDocs.java
Labels: ✨Feature, 문재경

#60 [Feat/#52] 팀, 팀 멤버에 로그인 기능 적용
  src/main/java/team4/footwithme/config/redis/ExternalRedisConfig.java
  src/main/java/team4/footwithme/global/domain/BaseEntity.java
  src/main/java/team4/footwithme/team/api/TeamApi.java
  src/main/java/team4/footwithme/team/api/TeamMemberApi.java
  src/main/java/team4/footwithme/team/domain/Team.java
  src/main/java/team4/footwithme/team/domain/TeamMember.java
  src/main/java/team4/footwithme/team/repository/CustomTeamMemberRepository.java
  src/main/java/team4/footwithme/team/repository/CustomTeamMemberRepositoryImpl.java
  src/main/java/team4/footwithme/team/repository/CustomTeamRepository.java
  src/main/java/team4/footwithme/team/repository/CustomTeamRepositoryImpl.java
  src/main/java/team4/footwithme/team/repository/TeamMemberRepository.java
  src/main/java/team4/footwithme/team/repository/TeamRepository.java
  src/main/java/team4/footwithme/team/service/TeamMemberService.java
  src/main/java/team4/footwithme/team/service/TeamMemberServiceImpl.java
  src/main/java/team4/footwithme/team/service/TeamService.java
  src/main/java/team4/footwithme/team/service/TeamServiceImpl.java
  src/test/java/team4/footwithme/team/service/TeamMemberServiceImplTest.java
  src/test/java/team4/footwithme/team/service/TeamServiceImplTest.java
  src/test/java/team4/footwithme/vote/service/VoteServiceImplTest.java
Labels: 🔥BugFix, ✨Feature, 박윤영

#63 [Feat/#51] 테스트 코드 작성 및 RESTDocs 사용
  src/docs/asciidoc/api/stadium/court.adoc
  src/docs/asciidoc/api/stadium/courtMerchant.adoc
  src/docs/asciidoc/api/stadium/stadium.adoc
  src/docs/asciidoc/api/stadium/stadiumMerchant.adoc
  src/main/java/team4/footwithme/stadium/repository/CourtRepository.java
  src/main/java/team4/footwithme/stadium/repository/StadiumRepository.java
  src/main/java/team4/footwithme/stadium/service/StadiumServiceImpl.java
  src/test/java/team4/footwithme/docs/stadium/CourtApiDocs.java
  src/test/java/team4/footwithme/docs/stadium/CourtMerchantApiDocs.java
  src/test/java/team4/footwithme/docs/stadium/StadiumApiDocs.java
  src/test/java/team4/footwithme/docs/stadium/StadiumMerchantApiDocs.java
  src/test/java/team4/footwithme/stadium/api/CourtApiTest.java
  src/test/java/team4/footwithme/stadium/api/CourtMerchantApiTest.java
  src/test/java/team4/footwithme/stadium/api/StadiumApiTest.java
  src/test/java/team4/footwithme/stadium/api/StadiumMerchantApiTest.java
  src/test/java/team4/footwithme/stadium/repository/CourtRepositoryTest.java
  src/test/java/team4/footwithme/stadium/repository/CustomStadiumRepositoryImplTest.java
  src/test/java/team4/footwithme/stadium/repository/StadiumRepositoryTest.java
  src/test/java/team4/footwithme/stadium/service/CourtServiceImplTest.java
  src/test/java/team4/footwithme/stadium/service/StadiumServiceImplTest.java
Labels: 📃 Docs, 노관태, 🧪Test

#71 Feat/#65 security
  src/main/java/team4/footwithme/config/SecurityConfig.java
  src/main/java/team4/footwithme/member/api/MemberApi.java
  src/main/java/team4/footwithme/member/jwt/PrincipalDetails.java
  src/main/java/team4/footwithme/member/jwt/PrincipalDetailsService.java
  src/main/java/team4/footwithme/member/service/MemberService.java
  src/main/java/team4/footwithme/member/service/MemberServiceImpl.java
  src/test/java/team4/footwithme/docs/member/MemberApiDocs.java
  src/test/java/team4/footwithme/member/service/MemberServiceImplTest.java
  src/test/java/team4/footwithme/team/service/TeamMemberServiceImplTest.java
Labels: ✨Feature, 문재경

#72 [feat/#37] 채팅 API test 및 RestDocs 구현
  src/docs/asciidoc/api/chat/chat.adoc
  src/docs/asciidoc/api/chat/chatMember.adoc
  src/docs/asciidoc/api/chat/chatroom.adoc
  src/main/java/team4/footwithme/chat/api/ChatApi.java
  src/main/java/team4/footwithme/chat/repository/CustomChatRepositoryImpl.java
  src/main/java/team4/footwithme/chat/service/ChatService.java
  src/main/java/team4/footwithme/chat/service/ChatServiceImpl.java
  src/main/java/team4/footwithme/config/redis/EmbeddedRedisConfig.java
  src/test/java/team4/footwithme/ApiTestSupport.java
  src/test/java/team4/footwithme/chat/api/ChatApiTest.java
  src/test/java/team4/footwithme/chat/api/ChatMemberApiTest.java
  src/test/java/team4/footwithme/chat/api/ChatroomApiTest.java
  src/test/java/team4/footwithme/docs/RestDocsSupport.java
  src/test/java/team4/footwithme/docs/chat/ChatApiDocs.java
  src/test/java/team4/footwithme/docs/chat/ChatMemberApiDocs.java
  src/test/java/team4/footwithme/docs/chat/ChatroomApiDocs.java
  src/test/java/team4/footwithme/security/CustomSecurityContextFactory.java
  src/test/java/team4/footwithme/security/WithMockPrincipalDetail.java
  src/test/java/team4/footwithme/team/service/TeamMemberServiceImplTest.java
Labels: 📃 Docs, 황민우, 🧪Test

#77 [feat/#68] 용병 관련 기능 API 구현
  src/main/java/team4/footwithme/global/exception/ExceptionMessage.java
  src/main/java/team4/footwithme/resevation/api/MWMercenaryApi.java
  src/main/java/team4/footwithme/resevation/api/MWParticipantApi.java
  src/main/java/team4/footwithme/resevation/api/request/MWMercenaryRequest.java
  src/main/java/team4/footwithme/resevation/api/request/MWParticipantUpdateRequest.java
  src/main/java/team4/footwithme/resevation/domain/Mercenary.java
  src/main/java/team4/footwithme/resevation/domain/Participant.java
  src/main/java/team4/footwithme/resevation/repository/CustomMercenaryRepository.java
  src/main/java/team4/footwithme/resevation/repository/CustomMercenaryRepositoryImpl.java
  src/main/java/team4/footwithme/resevation/repository/CustomParticipantRepository.java
  src/main/java/team4/footwithme/resevation/repository/CustomParticipantRepositoryImpl.java
  src/main/java/team4/footwithme/resevation/repository/MWParticipantRepository.java
  src/main/java/team4/footwithme/resevation/repository/MWReservationRepository.java
  src/main/java/team4/footwithme/resevation/repository/MercenaryRepository.java
  src/main/java/team4/footwithme/resevation/service/MWParticipantServiceImpl.java
  src/main/java/team4/footwithme/resevation/service/MercenaryServiceImpl.java
  src/main/java/team4/footwithme/resevation/service/request/MWMercenaryServiceRequest.java
  src/main/java/team4/footwithme/resevation/service/request/MWParticipantUpdateServiceRequest.java
  src/main/java/team4/footwithme/resevation/service/response/MWMercenaryResponse.java
  src/main/java/team4/footwithme/resevation/service/response/MWParticipantMemberInfo.java
  src/main/java/team4/footwithme/resevation/service/response/MWParticipantResponse.java
Labels: ✨Feature, 황민우

#74 [Feat/#69] 투표 종료시 예약 생성 구현
  src/main/java/team4/footwithme/resevation/domain/Mercenary.java
  src/main/java/team4/footwithme/resevation/domain/ParticipantGender.java
  src/main/java/team4/footwithme/resevation/domain/Reservation.java
  src/main/java/team4/footwithme/resevation/domain/ReservationStatus.java
  src/main/java/team4/footwithme/resevation/service/ReservationEventHandler.java
  src/main/java/team4/footwithme/resevation/service/ReservationService.java
  src/main/java/team4/footwithme/resevation/service/ReservationServiceImpl.java
  src/main/java/team4/footwithme/vote/repository/CustomChoiceRepository.java
  src/main/java/team4/footwithme/vote/repository/CustomChoiceRepositoryImpl.java
  src/main/java/team4/footwithme/vote/repository/CustomVoteItemRepository.java
  src/main/java/team4/footwithme/vote/repository/CustomVoteItemRepositoryImpl.java
  src/main/java/team4/footwithme/vote/repository/CustomVoteRepository.java
  src/main/java/team4/footwithme/vote/repository/CustomVoteRepositoryImpl.java
  src/main/java/team4/footwithme/vote/repository/VoteItemRepository.java
  src/main/java/team4/footwithme/vote/service/EndVoteEvent.java
  src/main/java/team4/footwithme/vote/service/VoteEventHandler.java
  src/main/java/team4/footwithme/vote/service/VoteItemService.java
  src/main/java/team4/footwithme/vote/service/VoteItemServiceImpl.java
  src/test/java/team4/footwithme/docs/vote/ChoiceApiDocs.java
  src/test/java/team4/footwithme/docs/vote/VoteApiDocs.java
  src/test/java/team4/footwithme/resevation/service/ReservationServiceImplTest.java
  src/test/java/team4/footwithme/team/service/TeamMemberServiceImplTest.java
  src/test/java/team4/footwithme/vote/api/VoteApiTest.java
  src/test/java/team4/footwithme/vote/repository/CustomChoiceRepositoryImplTest.java
Labels: ✨Feature, 나민혁

#76 [Feat/#64] 인증 필요한 API 테스트 코드 작성 및 RESTDocs 작성
  src/docs/asciidoc/api/stadium/court.adoc
  src/docs/asciidoc/api/stadium/courtMerchant.adoc
  src/docs/asciidoc/api/stadium/stadium.adoc
  src/docs/asciidoc/api/stadium/stadiumMerchant.adoc
  src/main/java/team4/footwithme/stadium/api/CourtMerchantApi.java
  src/main/java/team4/footwithme/stadium/api/StadiumMerchantApi.java
  src/main/java/team4/footwithme/stadium/service/CourtService.java
  src/main/java/team4/footwithme/stadium/service/CourtServiceImpl.java
  src/main/java/team4/footwithme/stadium/service/StadiumService.java
  src/main/java/team4/footwithme/stadium/service/StadiumServiceImpl.java
  src/test/java/team4/footwithme/ApiTestSupport.java
  src/test/java/team4/footwithme/docs/stadium/CourtMerchantApiDocs.java
  src/test/java/team4/footwithme/docs/stadium/StadiumMerchantApiDocs.java
  src/test/java/team4/footwithme/stadium/api/CourtApiTest.java
  src/test/java/team4/footwithme/stadium/api/CourtMerchantApiTest.java
  src/test/java/team4/footwithme/stadium/api/StadiumApiTest.java
  src/test/java/team4/footwithme/stadium/api/StadiumMerchantApiTest.java
  src/test/java/team4/footwithme/stadium/service/CourtServiceImplTest.java
  src/test/java/team4/footwithme/stadium/service/StadiumServiceImplTest.java
Labels: 📃 Docs, 노관태, 🧪Test

#79 [Feat/#70] 팀, 팀 멤버 RestDocs 테스트 코드 작성
  src/docs/asciidoc/api/team/team.adoc
  src/docs/asciidoc/api/team/teamMember.adoc
  src/test/java/team4/footwithme/docs/team/TeamApiDocs.java
  src/test/java/team4/footwithme/docs/team/TeamMemberApiDocs.java
Labels: ✨Feature, 박윤영

#80 [Feat/#73] 예약 취소 기능 구현
  src/main/java/team4/footwithme/resevation/api/JKReservationApi.java
  src/main/java/team4/footwithme/resevation/domain/Game.java
  src/main/java/team4/footwithme/resevation/domain/Mercenary.java
  src/main/java/team4/footwithme/resevation/domain/Reservation.java
  src/main/java/team4/footwithme/resevation/repository/JKGameRepository.java
  src/main/java/team4/footwithme/resevation/repository/JKMercenaryRepository.java
  src/main/java/team4/footwithme/resevation/repository/JKParticipantRepository.java
  src/main/java/team4/footwithme/resevation/service/JKReservationService.java
  src/main/java/team4/footwithme/resevation/service/JKReservationServiceImpl.java
  src/test/java/team4/footwithme/docs/reservation/JKReservationApiDocs.java
  src/test/java/team4/footwithme/resevation/service/JKReservationServiceImplTest.java
Labels: ✨Feature, 문재경

#81 [Feat/#75] 테스트 추가 작성 및 문서화
  src/docs/asciidoc/api/vote/choice.adoc
  src/docs/asciidoc/api/vote/vote.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/team4/footwithme/vote/api/VoteApi.java
  src/main/java/team4/footwithme/vote/api/request/DateChoices.java
  src/main/java/team4/footwithme/vote/api/request/VoteDateCreateRequest.java
  src/main/java/team4/footwithme/vote/api/request/VoteUpdateRequest.java
  src/main/java/team4/footwithme/vote/api/request/annotation/Duplicate.java
  src/main/java/team4/footwithme/vote/domain/Choice.java
  src/main/java/team4/footwithme/vote/domain/Vote.java
  src/main/java/team4/footwithme/vote/repository/CustomVoteRepository.java
  src/main/java/team4/footwithme/vote/repository/CustomVoteRepositoryImpl.java
  src/main/java/team4/footwithme/vote/service/EndVoteEvent.java
  src/main/java/team4/footwithme/vote/service/VoteEventHandler.java
  src/main/java/team4/footwithme/vote/service/VoteService.java
  src/main/java/team4/footwithme/vote/service/VoteServiceImpl.java
  src/main/java/team4/footwithme/vote/service/request/VoteUpdateServiceRequest.java
  src/main/java/team4/footwithme/vote/service/response/AllVoteResponse.java
  src/main/java/team4/footwithme/vote/service/response/VoteItemResponse.java
  src/test/java/team4/footwithme/docs/vote/VoteApiDocs.java
  src/test/java/team4/footwithme/vote/repository/CustomVoteRepositoryImplTest.java
  src/test/java/team4/footwithme/vote/service/VoteServiceImplTest.java
Labels: ✨Feature, 나민혁

#82 [Feat/#67] 예약 조회 및 게임 신청, 수락, 거절
  src/main/java/team4/footwithme/global/exception/ExceptionMessage.java
  src/main/java/team4/footwithme/resevation/api/GameApi.java
  src/main/java/team4/footwithme/resevation/api/ReservationApi.java
  src/main/java/team4/footwithme/resevation/api/request/GameRegisterRequest.java
  src/main/java/team4/footwithme/resevation/api/request/GameStatusUpdateRequest.java
  src/main/java/team4/footwithme/resevation/domain/Game.java
  src/main/java/team4/footwithme/resevation/domain/Reservation.java
  src/main/java/team4/footwithme/resevation/domain/ReservationStatus.java
  src/main/java/team4/footwithme/resevation/repository/GameRepository.java
  src/main/java/team4/footwithme/resevation/repository/ReservationRepository.java
  src/main/java/team4/footwithme/resevation/service/GameService.java
  src/main/java/team4/footwithme/resevation/service/GameServiceImpl.java
  src/main/java/team4/footwithme/resevation/service/ReservationService.java
  src/main/java/team4/footwithme/resevation/service/ReservationServiceImpl.java
  src/main/java/team4/footwithme/resevation/service/request/GameRegisterServiceRequest.java
  src/main/java/team4/footwithme/resevation/service/request/GameStatusUpdateServiceRequest.java
  src/main/java/team4/footwithme/resevation/service/response/GameDetailResponse.java
  src/main/java/team4/footwithme/resevation/service/response/ReservationsResponse.java
  src/test/java/team4/footwithme/resevation/repository/GameRepositoryTest.java
  src/test/java/team4/footwithme/resevation/service/GameServiceImplTest.java
Labels: ✨Feature, 노관태

#86 [Feat/#66] 멤버 테스트 코드 및 RestDocs 작성
  src/docs/asciidoc/api/member/member.adoc
  src/test/java/team4/footwithme/ApiTestSupport.java
  src/test/java/team4/footwithme/docs/member/MemberApiDocs.java
  src/test/java/team4/footwithme/member/api/MemberApiTest.java
  src/test/java/team4/footwithme/member/service/MemberServiceImplTest.java
Labels: ✨Feature, 문재경

#87 [feat/#78] 용병 및 예약 참가 인원 테스트 코드, Rest Docs 작성
  src/docs/asciidoc/api/mercenary/mercenary.adoc
  src/docs/asciidoc/api/participant/participant.adoc
  src/main/java/team4/footwithme/resevation/repository/MWParticipantRepository.java
  src/main/java/team4/footwithme/resevation/repository/MWReservationRepository.java
  src/test/java/team4/footwithme/ApiTestSupport.java
  src/test/java/team4/footwithme/docs/mercenary/MWMercenaryApiDocs.java
  src/test/java/team4/footwithme/docs/participant/MWParticipantApiDocs.java
  src/test/java/team4/footwithme/mercenary/api/MWMercenaryApiTest.java
  src/test/java/team4/footwithme/paricipant/api/MWParticipantApiTest.java
Labels: 📃 Docs, 황민우, 🧪Test

#89 [fix/#85] 투표 종료시 예약으로 넘어가는 조건 수정
  src/main/java/team4/footwithme/vote/repository/CustomChoiceRepositoryImpl.java
  src/main/java/team4/footwithme/vote/repository/CustomVoteRepositoryImpl.java
  src/main/java/team4/footwithme/vote/service/VoteEventHandler.java
  src/main/java/team4/footwithme/vote/service/VoteService.java
  src/main/java/team4/footwithme/vote/service/VoteServiceImpl.java
Labels: 🔥BugFix, 나민혁

#88 [feat: #83] 팀 경기 일정조회 및 일정 상세 조회 기능 구현
  src/docs/asciidoc/api/reservation/reservation.adoc
  src/main/java/team4/footwithme/resevation/api/YYReservationApi.java
  src/main/java/team4/footwithme/resevation/repository/YYGameRepository.java
  src/main/java/team4/footwithme/resevation/repository/YYReservationRepository.java
  src/main/java/team4/footwithme/resevation/service/YYReservationService.java
  src/main/java/team4/footwithme/resevation/service/YYReservationServiceImpl.java
  src/main/java/team4/footwithme/resevation/service/response/YYParticipantResponse.java
  src/main/java/team4/footwithme/resevation/service/response/YYReservationInfoDetailsResponse.java
  src/main/java/team4/footwithme/resevation/service/response/YYReservationInfoResponse.java
  src/main/java/team4/footwithme/team/api/TeamApi.java
  src/test/java/team4/footwithme/docs/reservation/YYReservationApiDocs.java
Labels: 📃 Docs, ✨Feature, 박윤영, 🧪Test

#90 [Feat/#84] reservation 테스트 코드 및 RESTDocs 작성
  src/docs/asciidoc/api/game/game.adoc
  src/docs/asciidoc/api/reservation/reservation.adoc
  src/main/java/team4/footwithme/global/exception/ExceptionMessage.java
  src/main/java/team4/footwithme/resevation/api/GameApi.java
  src/main/java/team4/footwithme/resevation/api/request/GameStatusUpdateRequest.java
  src/main/java/team4/footwithme/resevation/repository/GameRepository.java
  src/main/java/team4/footwithme/resevation/repository/ReservationRepository.java
  src/main/java/team4/footwithme/resevation/service/GameServiceImpl.java
  src/main/java/team4/footwithme/resevation/service/ReservationServiceImpl.java
  src/main/java/team4/footwithme/resevation/service/response/ReservationsResponse.java
  src/test/java/team4/footwithme/ApiTestSupport.java
  src/test/java/team4/footwithme/docs/reservation/GameApiDocs.java
  src/test/java/team4/footwithme/docs/reservation/ReservationApiDocs.java
  src/test/java/team4/footwithme/docs/stadium/CourtApiDocs.java
  src/test/java/team4/footwithme/docs/stadium/CourtMerchantApiDocs.java
  src/test/java/team4/footwithme/docs/stadium/StadiumApiDocs.java
  src/test/java/team4/footwithme/docs/stadium/StadiumMerchantApiDocs.java
  src/test/java/team4/footwithme/resevation/api/GameApiTest.java
  src/test/java/team4/footwithme/resevation/api/ReservationApiTest.java
  src/test/java/team4/footwithme/resevation/repository/GameRepositoryTest.java
  src/test/java/team4/footwithme/resevation/service/ReservationServiceImplTest.java
  src/test/java/team4/footwithme/stadium/api/CourtApiTest.java
  src/test/java/team4/footwithme/stadium/api/CourtMerchantApiTest.java
  src/test/java/team4/footwithme/stadium/api/StadiumApiTest.java
  src/test/java/team4/footwithme/stadium/repository/CustomCourtRepositoryImplTest.java
  src/test/java/team4/footwithme/stadium/repository/CustomStadiumRepositoryImplTest.java
Labels: 📃 Docs, 🔨Refactor, 노관태, 🧪Test

#95 [fix/#94] 웹소켓 접속 문제 해결
  src/main/java/team4/footwithme/config/SecurityConfig.java
Labels: 🔥BugFix, 황민우

#100 [feat/#99] 부족한 기능들 추가
  src/docs/asciidoc/api/chat/chatroom.adoc
  src/docs/asciidoc/api/reservation/reservation.adoc
  src/main/java/team4/footwithme/chat/api/ChatroomApi.java
  src/main/java/team4/footwithme/chat/repository/ChatroomRepository.java
  src/main/java/team4/footwithme/chat/service/ChatroomService.java
  src/main/java/team4/footwithme/chat/service/ChatroomServiceImpl.java
  src/main/java/team4/footwithme/resevation/api/ReservationApi.java
  src/main/java/team4/footwithme/resevation/api/request/ReservationUpdateRequest.java
  src/main/java/team4/footwithme/resevation/domain/Reservation.java
  src/main/java/team4/footwithme/resevation/service/ReservationService.java
  src/main/java/team4/footwithme/resevation/service/ReservationServiceImpl.java
  src/main/java/team4/footwithme/resevation/service/request/ReservationUpdateServiceRequest.java
  src/main/java/team4/footwithme/team/service/TeamServiceImpl.java
  src/test/java/team4/footwithme/docs/chat/ChatroomApiDocs.java
  src/test/java/team4/footwithme/docs/reservation/ReservationApiDocs.java
Labels: 📃 Docs, ✨Feature, 황민우

#105 [Refactor/#104] 투표종료에 따른 예약 메서드 리팩토링
  src/main/java/team4/footwithme/resevation/domain/Reservation.java
  src/main/java/team4/footwithme/resevation/service/ReservationServiceImpl.java
  src/main/java/team4/footwithme/vote/service/VoteServiceImpl.java
Labels: 🔨Refactor, 나민혁
