Repository prgrms-be-devcourse/NBE1_2_Team04, pull requests merged in 2024-09, with the labels that each got.

#8 [feat/#2] 장소 투표 생성 및 조회 구현
  .github/pull_request_template.md
  src/docs/asciidoc/api/vote/vote.adoc
  src/docs/asciidoc/index.adoc
  src/main/java/team4/footwithme/member/repository/CustomMemberRepository.java
  src/main/java/team4/footwithme/member/repository/CustomMemberRepositoryImpl.java
  src/main/java/team4/footwithme/member/repository/MemberRepository.java
  src/main/java/team4/footwithme/resevation/domain/Game.java
  src/main/java/team4/footwithme/resevation/domain/GameStatus.java
  src/main/java/team4/footwithme/resevation/repository/MatchRepository.java
  src/main/java/team4/footwithme/stadium/repository/CustomStadiumRepository.java
  src/main/java/team4/footwithme/stadium/repository/CustomStadiumRepositoryImpl.java
  src/main/java/team4/footwithme/stadium/repository/StadiumRepository.java
  src/main/java/team4/footwithme/vote/api/VoteApi.java
  src/main/java/team4/footwithme/vote/api/request/StadiumChoices.java
  src/main/java/team4/footwithme/vote/api/request/VoteStadiumCreateRequest.java
  src/main/java/team4/footwithme/vote/api/request/annotation/Duplicate.java
  src/main/java/team4/footwithme/vote/api/request/annotation/validator/DuplicateValidator.java
  src/main/java/team4/footwithme/vote/domain/Choice.java
  src/main/java/team4/footwithme/vote/domain/ChoiceDate.java
  src/main/java/team4/footwithme/vote/domain/ChoiceLocate.java
  src/main/java/team4/footwithme/vote/domain/Vote.java
  src/main/java/team4/footwithme/vote/domain/VoteItem.java
  src/main/java/team4/footwithme/vote/domain/VoteItemDate.java
  src/main/java/team4/footwithme/vote/domain/VoteItemLocate.java
  src/main/java/team4/footwithme/vote/repository/ChoiceRepository.java
  src/main/java/team4/footwithme/vote/repository/CustomChoiceRepository.java
  src/main/java/team4/footwithme/vote/repository/CustomChoiceRepositoryImpl.java
  src/main/java/team4/footwithme/vote/repository/CustomVoteRepository.java
  src/main/java/team4/footwithme/vote/repository/CustomVoteRepositoryImpl.java
  src/main/java/team4/footwithme/vote/repository/VoteItemRepository.java
  src/main/java/team4/footwithme/vote/repository/VoteRepository.java
  src/main/java/team4/footwithme/vote/service/VoteItemService.java
  src/main/java/team4/footwithme/vote/service/VoteItemServiceImpl.java
  src/main/java/team4/footwithme/vote/service/VoteService.java
  src/main/java/team4/footwithme/vote/service/VoteServiceImpl.java
  src/main/java/team4/footwithme/vote/service/request/VoteStadiumCreateServiceRequest.java
  src/main/java/team4/footwithme/vote/service/response/VoteItemResponse.java
  src/main/java/team4/footwithme/vote/service/response/VoteResponse.java
  src/test/java/team4/footwithme/ApiTestSupport.java
  src/test/java/team4/footwithme/docs/RestDocsSupport.java
  src/test/java/team4/footwithme/docs/vote/VoteApiDocs.java
  src/test/java/team4/footwithme/member/repository/CustomMemberRepositoryImplTest.java
  src/test/java/team4/footwithme/stadium/repository/CustomStadiumRepositoryImplTest.java
  src/test/java/team4/footwithme/vote/api/VoteApiTest.java
  src/test/java/team4/footwithme/vote/domain/VoteTest.java
  src/test/java/team4/footwithme/vote/repository/VoteItemRepositoryTest.java
  src/test/java/team4/footwithme/vote/service/VoteServiceImplTest.java
  src/test/resources/application-test.yaml
Labels: ✨Feature, 나민혁

#12 [Feat/#6] Jwt 토큰과 Security 및 Redis 설정
  build.gradle
  src/main/java/team4/footwithme/config/CorsConfig.java
  src/main/java/team4/footwithme/config/RedisConfig.java
  src/main/java/team4/footwithme/config/SecurityConfig.java
  src/main/java/team4/footwithme/member/domain/Member.java
  src/main/java/team4/footwithme/member/jwt/JwtTokenFilter.java
  src/main/java/team4/footwithme/member/jwt/JwtTokenUtil.java
  src/main/java/team4/footwithme/member/jwt/PrincipalDetails.java
  src/main/java/team4/footwithme/member/jwt/PrincipalDetailsService.java
  src/main/java/team4/footwithme/member/jwt/response/TokenResponse.java
  src/main/java/team4/footwithme/member/repository/MemberRepository.java
  src/main/java/team4/footwithme/member/service/CookieService.java
  src/test/java/team4/footwithme/IntegrationTestSupport.java
  src/test/java/team4/footwithme/member/jwt/JwtTokenUtilTest.java
  src/test/java/team4/footwithme/member/repository/MemberRepositoryTest.java
Labels: ✨Feature, 문재경

#14 [Feat/#5] 팀 생성 기능 및 팀 정보 조회 기능 구현
  src/main/java/team4/footwithme/resevation/api/GameApi.java
  src/main/java/team4/footwithme/resevation/service/GameService.java
  src/main/java/team4/footwithme/resevation/service/GameServiceImpl.java
  src/main/java/team4/footwithme/team/api/TeamApi.java
  src/main/java/team4/footwithme/team/api/request/TeamCreateRequest.java
  src/main/java/team4/footwithme/team/domain/Team.java
  src/main/java/team4/footwithme/team/domain/TeamRate.java
  src/main/java/team4/footwithme/team/domain/TotalRecord.java
  src/main/java/team4/footwithme/team/repository/TeamMemberRepository.java
  src/main/java/team4/footwithme/team/repository/TeamRateRepository.java
  src/main/java/team4/footwithme/team/repository/TeamRepository.java
  src/main/java/team4/footwithme/team/service/TeamService.java
  src/main/java/team4/footwithme/team/service/TeamServiceImpl.java
  src/main/java/team4/footwithme/team/service/request/TeamCreateServiceRequest.java
  src/main/java/team4/footwithme/team/service/response/TeamCreatedResponse.java
  src/main/java/team4/footwithme/team/service/response/TeamInfoResponse.java
  src/main/resources/application.yaml
  src/test/java/team4/footwithme/team/service/TeamServiceImplTest.java
Labels: ✨Feature, 박윤영

#20 [Fix/#19] 테스트 환경 수정 및 시큐리티 테스트 설정
  .gitignore
  src/main/java/team4/footwithme/config/SecurityConfig.java
  src/main/resources/application.yaml
  src/test/java/team4/footwithme/ApiTestSupport.java
  src/test/java/team4/footwithme/IntegrationTestSupport.java
  src/test/java/team4/footwithme/vote/api/VoteApiTest.java
  src/test/resources/application-test.yaml
Labels: 🔥BugFix, 나민혁

#24 [fix/#23] 런타임 에러 해결 및 테스트 수정
  src/main/java/team4/footwithme/team/repository/TeamMemberRepository.java
  src/test/java/team4/footwithme/vote/service/VoteServiceImplTest.java
Labels: 🔥BugFix, 나민혁

#15 [Feat/#7] 구장 관련 기능 일부 구현
  build.gradle
  src/main/java/team4/footwithme/global/util/PositionUtil.java
  src/main/java/team4/footwithme/stadium/api/CourtApi.java
  src/main/java/team4/footwithme/stadium/api/StadiumApi.java
  src/main/java/team4/footwithme/stadium/api/request/StadiumRegisterRequest.java
  src/main/java/team4/footwithme/stadium/api/request/StadiumSearchByLocationRequest.java
  src/main/java/team4/footwithme/stadium/domain/Court.java
  src/main/java/team4/footwithme/stadium/domain/Stadium.java
  src/main/java/team4/footwithme/stadium/exception/StadiumException.java
  src/main/java/team4/footwithme/stadium/exception/StadiumExceptionMessage.java
  src/main/java/team4/footwithme/stadium/repository/StadiumRepository.java
  src/main/java/team4/footwithme/stadium/repository/StadiumRepositoryCustom.java
  src/main/java/team4/footwithme/stadium/repository/StadiumRepositoryCustomImpl.java
  src/main/java/team4/footwithme/stadium/service/StadiumService.java
  src/main/java/team4/footwithme/stadium/service/StadiumServiceImpl.java
  src/main/java/team4/footwithme/stadium/service/request/StadiumSearchByLocationServiceRequest.java
  src/main/java/team4/footwithme/stadium/service/response/StadiumDetailResponse.java
  src/main/java/team4/footwithme/stadium/service/response/StadiumsResponse.java
  src/test/java/team4/footwithme/stadium/service/StadiumServiceImplTest.java
Labels: ✨Feature, 노관태

#22 [feat]/#3 채팅 기능 일부 구현
  build.gradle
  src/main/java/team4/footwithme/chat/domain/Chat.java
  src/main/java/team4/footwithme/chat/domain/ChatMember.java
  src/main/java/team4/footwithme/chat/domain/Chatroom.java
  src/main/java/team4/footwithme/chat/repository/ChatMemberRepository.java
  src/main/java/team4/footwithme/chat/repository/ChatRepository.java
  src/main/java/team4/footwithme/chat/repository/ChatroomRepository.java
  src/main/java/team4/footwithme/chat/repository/RedisChatroomRepository.java
  src/main/java/team4/footwithme/chat/service/ChatMemberServiceImpl.java
  src/main/java/team4/footwithme/chat/service/ChatServiceImpl.java
  src/main/java/team4/footwithme/chat/service/ChatroomServiceImpl.java
  src/main/java/team4/footwithme/chat/service/RedisPublisher.java
  src/main/java/team4/footwithme/chat/service/RedisSubscriber.java
  src/main/java/team4/footwithme/chat/service/request/ChatMemberServiceRequest.java
  src/main/java/team4/footwithme/chat/service/request/ChatServiceRequest.java
  src/main/java/team4/footwithme/chat/service/response/ChatMemberInfo.java
  src/main/java/team4/footwithme/chat/service/response/ChatResponse.java
  src/main/java/team4/footwithme/chat/service/response/ChatroomInfo.java
  src/main/java/team4/footwithme/chat/service/response/ChatroomResponse.java
  src/main/java/team4/footwithme/config/RedisConfig.java
  src/main/java/team4/footwithme/config/redis/EmbeddedRedisConfig.java
  src/main/java/team4/footwithme/config/redis/RedisConfig.java
  src/main/java/team4/footwithme/config/websocket/WebSocketConfig.java
  src/main/java/team4/footwithme/member/repository/MemberRepository.java
  src/main/java/team4/footwithme/resevation/domain/Game.java
  src/main/java/team4/footwithme/resevation/repository/GameRepository.java
  src/main/java/team4/footwithme/resevation/service/GameServiceImpl.java
Labels: ✨Feature, 황민우

#29 [Feat/#9] 일정 투표 생성,조회,삭제
  src/docs/asciidoc/api/vote/vote.adoc
  src/main/java/team4/footwithme/config/SecurityConfig.java
  src/main/java/team4/footwithme/config/redis/EmbeddedRedisConfig.java
  src/main/java/team4/footwithme/vote/api/VoteApi.java
  src/main/java/team4/footwithme/vote/api/request/DateChoices.java
  src/main/java/team4/footwithme/vote/api/request/VoteDateCreateRequest.java
  src/main/java/team4/footwithme/vote/domain/VoteItemDate.java
  src/main/java/team4/footwithme/vote/repository/CustomChoiceRepositoryImpl.java
  src/main/java/team4/footwithme/vote/repository/VoteItemRepository.java
  src/main/java/team4/footwithme/vote/service/VoteService.java
  src/main/java/team4/footwithme/vote/service/VoteServiceImpl.java
  src/main/java/team4/footwithme/vote/service/request/VoteDateCreateServiceRequest.java
  src/test/java/team4/footwithme/docs/vote/VoteApiDocs.java
  src/test/java/team4/footwithme/stadium/service/StadiumServiceImplTest.java
  src/test/java/team4/footwithme/vote/repository/VoteItemRepositoryTest.java
  src/test/java/team4/footwithme/vote/service/VoteServiceImplTest.java
Labels: ✨Feature, 나민혁

#26 [Feat/#13] 회원가입, 로그인 API 구현
  src/main/java/team4/footwithme/member/api/MemberApi.java
  src/main/java/team4/footwithme/member/api/request/JoinRequest.java
  src/main/java/team4/footwithme/member/api/request/LoginRequest.java
  src/main/java/team4/footwithme/member/domain/LoginType.java
  src/main/java/team4/footwithme/member/domain/Member.java
  src/main/java/team4/footwithme/member/repository/CustomMemberRepository.java
  src/main/java/team4/footwithme/member/repository/CustomMemberRepositoryImpl.java
  src/main/java/team4/footwithme/member/repository/MemberRepository.java
  src/main/java/team4/footwithme/member/service/CookieService.java
  src/main/java/team4/footwithme/member/service/MemberService.java
  src/main/java/team4/footwithme/member/service/MemberServiceImpl.java
  src/main/java/team4/footwithme/member/service/request/JoinServiceRequest.java
  src/main/java/team4/footwithme/member/service/request/LoginServiceRequest.java
  src/main/java/team4/footwithme/member/service/response/LoginResponse.java
  src/main/java/team4/footwithme/member/service/response/MemberResponse.java
  src/test/java/team4/footwithme/docs/member/MemberApiDocs.java
  src/test/java/team4/footwithme/member/jwt/JwtTokenUtilTest.java
  src/test/java/team4/footwithme/member/repository/MemberRepositoryTest.java
  src/test/java/team4/footwithme/member/service/MemberServiceImplTest.java
Labels: ✨Feature, 문재경

#38 [Feat/#10] 투표하기 투표 취소하기, 투표 수정 구현
  src/main/java/team4/footwithme/chat/api/ChatApi.java
  src/main/java/team4/footwithme/chat/repository/CustomChatRepositoryImpl.java
  src/main/java/team4/footwithme/chat/repository/RedisChatroomRepository.java
  src/main/java/team4/footwithme/chat/service/ChatMemberServiceImpl.java
  src/main/java/team4/footwithme/chat/service/ChatServiceImpl.java
  src/main/java/team4/footwithme/chat/service/ChatroomServiceImpl.java
  src/main/java/team4/footwithme/chat/service/RedisSubscriber.java
  src/main/java/team4/footwithme/member/domain/Member.java
  src/main/java/team4/footwithme/member/service/CookieService.java
  src/main/java/team4/footwithme/member/service/MemberServiceImpl.java
  src/main/java/team4/footwithme/stadium/api/CourtApi.java
  src/main/java/team4/footwithme/stadium/repository/CustomStadiumRepository.java
  src/main/java/team4/footwithme/stadium/repository/CustomStadiumRepositoryImpl.java
  src/main/java/team4/footwithme/stadium/service/CourtService.java
  src/main/java/team4/footwithme/stadium/service/CourtServiceImpl.java
  src/main/java/team4/footwithme/stadium/service/StadiumServiceImpl.java
  src/main/java/team4/footwithme/stadium/service/response/CourtDetailResponse.java
  src/main/java/team4/footwithme/stadium/service/response/CourtsResponse.java
  src/main/java/team4/footwithme/team/api/TeamApi.java
  src/main/java/team4/footwithme/team/domain/Team.java
  src/main/java/team4/footwithme/team/repository/CustomTeamRepository.java
  src/main/java/team4/footwithme/team/service/TeamServiceImpl.java
  src/main/java/team4/footwithme/vote/api/ChoiceApi.java
  src/main/java/team4/footwithme/vote/api/VoteApi.java
  src/main/java/team4/footwithme/vote/api/request/ChoiceCreateRequest.java
  src/main/java/team4/footwithme/vote/api/request/VoteUpdateRequest.java
  src/main/java/team4/footwithme/vote/domain/Vote.java
  src/main/java/team4/footwithme/vote/domain/VoteItemDate.java
  src/main/java/team4/footwithme/vote/repository/CustomChoiceRepository.java
  src/main/java/team4/footwithme/vote/repository/CustomChoiceRepositoryImpl.java
  src/main/java/team4/footwithme/vote/repository/CustomVoteItemRepository.java
  src/main/java/team4/footwithme/vote/repository/CustomVoteItemRepositoryImpl.java
  src/main/java/team4/footwithme/vote/repository/VoteItemRepository.java
  src/main/java/team4/footwithme/vote/service/VoteService.java
  src/main/java/team4/footwithme/vote/service/VoteServiceImpl.java
  src/main/java/team4/footwithme/vote/service/request/ChoiceCreateServiceRequest.java
  src/main/java/team4/footwithme/vote/service/request/VoteUpdateServiceRequest.java
  src/test/java/team4/footwithme/docs/member/MemberApiDocs.java
  src/test/java/team4/footwithme/docs/vote/ChoiceApiDocs.java
  src/test/java/team4/footwithme/docs/vote/VoteApiDocs.java
  src/test/java/team4/footwithme/member/jwt/JwtTokenUtilTest.java
  src/test/java/team4/footwithme/member/repository/MemberRepositoryTest.java
  src/test/java/team4/footwithme/member/service/MemberServiceImplTest.java
  src/test/java/team4/footwithme/stadium/repository/CustomStadiumRepositoryImplTest.java
  src/test/java/team4/footwithme/stadium/service/CourtServiceImplTest.java
  src/test/java/team4/footwithme/stadium/service/StadiumServiceImplTest.java
  src/test/java/team4/footwithme/vote/domain/VoteItemDateTest.java
  src/test/java/team4/footwithme/vote/domain/VoteTest.java
  src/test/java/team4/footwithme/vote/repository/CustomChoiceRepositoryImplTest.java
  src/test/java/team4/footwithme/vote/repository/VoteItemRepositoryTest.java
  src/test/java/team4/footwithme/vote/service/VoteServiceImplTest.java
Labels: ✨Feature, 나민혁
